# ==== APP CONFIG ====

server.port=${SERVER_PORT}

# ==== DATABASE CONFIG ==== #

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

# ==== SECURITY CONFIG ==== #

api.security.token.secret=${SEC_KEY}
api.security.token.expirationTimeInHours=6
api.security.token.refreshExpirationTimeInHours=24

# ==== FEIGN CLIENTS ====

viacep.api.url=${VIACEP_URL}